#!/bin/bash
echo "Write the name of the new folder:"
read foldder1
echo "Write the TIME:"
read timmee
echo "HashCat Start!"
sudo systemctl stop NetworkManager.service
sudo systemctl stop wpa_supplicant.service
echo "1 Start!"
sudo hcxdumptool -i wlan1 -o dumpfile.pcapng --active_beacon --tot=$timmee --enable_status=15
echo "1 Done!!"
sudo systemctl start wpa_supplicant.service
sudo systemctl start NetworkManager.service
sudo hcxpcapngtool -o hash.hc22000 -E essidlist dumpfile.pcapng
echo "2 Start!"
sudo mkdir $foldder1
mv -v /home/kali/dumpfile.pcapng /home/kali/$foldder1
mv -v /home/kali/hash.hc22000 /home/kali/$foldder1
mv -v /home/kali/essidlist /home/kali/$foldder1
echo "2 Done!!"
echo "HashCat is Done!!!"
echo "System is down now!!!"
sudo shutdown now